import { SkillsList } from '../interfaces/skills.interface';

export const skills: SkillsList = [
  ['Typescript', 10],
  ['Javascript', 10],
  ['Angular', 10],
  ['Ionic', 10],
  ['Cordova', 10],
  ['Capacitor', 10],

  ['Node', 8],
  ['Express', 8],
  ['Knex', 8],

  ['React', 6],
  ['TransactSQL', 6],

  ['C#', 4],
  ['Vue', 4],
  ['React-Native', 2],
  ['Redux', 4],
  ['SQL Server', 3],
  ['PostgresSQL', 8],
  ['.NET Core', 4],
  ['MySQL', 8],
  ['FluentMigrator', 8],
  ['Linux Environments', 6],
  ['Linux Containers', 4],
  ['Docker', 6],
  ['Power-Bi Integrations', 8],
  ['ETL Processes', 1],
  ['ETL Automations', 1],
  ['Vue', 4],

  ['Protractor', 4],
  ['QA Automation', 4],
  ['Selenium', 4],
  ['Jest', 1],
  ['Unit Testing', 10],
  ['End-to-End Testing', 10],
  ['Cypress', 8],
  ['Jasmine', 1],
  ['Karma', 1],
  ['Mocha', 1],
  ['Chai', 1],
  ['Cypress', 8],
  ['Appium', 2],

  ['TFS', 1],
  ['Jira', 1],
  ['ADO', 1],
  ['Confluence', 1],
  ['Team Documentation', 1],
  ['Agile', 1],
  ['Scrum', 1],
  ['Kanban', 1],
  ['Git', 10],
  ['Github', 1],
  ['Bitbucket', 1],

  ['HTML', 8],
  ['CSS', 8],
  ['SCSS', 8],
  ['Bootstrap', 6],
  ['Flexbox', 1],

  ['Mentor', 10],
  ['Team Lead', 10],
];
