import { SkillsList } from '../interfaces/skills.interface';

export const skills: SkillsList = [
  ['Typescript', 20],
  ['Javascript', 20],
  ['Angular', 20],
  ['Ionic', 20],
  ['Cordova', 20],
  ['Capacitor', 20],
  ['Node', 8],
  ['Express', 8],
  ['Knex', 8],
  ['React', 6],
  ['TransactSQL', 6],
  ['C#', 5],
  ['Vue', 5],
  ['React-Native', 3],
  ['Redux', 5],
  ['SQL Server', 4],
  ['PostgresSQL', 8],
  ['.NET Core', 5],
  ['MySQL', 8],
  ['FluentMigrator', 8],
  ['Linux Environments', 6],
  ['Linux Containers', 5],
  ['Docker', 6],
  ['Power-Bi Integrations', 8],
  ['ETL Processes', 2],
  ['ETL Automations', 2],
  ['Vue', 5],
  ['Protractor', 5],
  ['QA Automation', 5],
  ['Selenium', 5],
  ['Jest', 2],
  ['Unit Testing', 20],
  ['End-to-End Testing', 20],
  ['Cypress', 8],
  ['Jasmine', 2],
  ['Karma', 2],
  ['Mocha', 2],
  ['Chai', 2],
  ['Cypress', 8],
  ['Appium', 3],
  ['TFS', 2],
  ['Jira', 2],
  ['ADO', 2],
  ['Confluence', 2],
  ['Team Documentation', 2],
  ['Agile', 2],
  ['Scrum', 2],
  ['Kanban', 2],
  ['Git', 20],
  ['Github', 2],
  ['Bitbucket', 2],
  ['HTML', 8],
  ['CSS', 8],
  ['SCSS', 8],
  ['Bootstrap', 6],
  ['Flexbox', 2],
  ['Mentor', 20],
  ['Team Lead', 20],
];
